name: Deploy
on:
  push:
    branches:
      - master
        - 
          
jobs:
  build:
    runs-on: macos-latest
    steps:
     run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/canvassky.git master
     usedocker: true
